
create table PUBLIC.CoherenceObjectEntity (
        id integer not null,
        comparableValue double,
        value varchar(1024) not null,
        property_id integer not null,
        primary key (id)
    )
 
    create table PUBLIC.EnvironmentEntity (
        id integer not null,
        created_by varchar(255),
        date_created bigint,
        date_modified bigint,
        modified_by varchar(255),
        name varchar(255) not null,
        primary key (id)
    )
 
    create table PUBLIC.EnvironmentEntity_InstanceEntity (
        environmentCollection_id integer not null,
        instanceCollection_id integer not null
    )
 
    create table PUBLIC.ExpressionEntity (
        id integer not null,
        isPositive boolean not null,
        level integer not null,
        modalityTypeId varchar(255),
        coherenceInformation_id integer not null,
        source_sourceId varchar(255),
        source_sourceType varchar(255),
        primary key (id)
    )
 
    create table PUBLIC.InstanceEntity (
        id integer not null,
        created_by varchar(255),
        date_created bigint,
        date_modified bigint,
        modified_by varchar(255),
        typeId varchar(255) not null,
        primary key (id)
    )
 
    create table PUBLIC.Member (
        id bigint generated by default as identity (start with 1),
        dateCreated bigint,
        dateModified bigint,
        deleted boolean,
        firstname varchar(32),
        lastname varchar(32),
        modifiedby varchar(255),
        organisation varchar(255),
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    )
 
    create table PUBLIC.PropertyEntity (
        id integer not null,
        path varchar(512) not null,
        instance_id integer not null,
        primary key (id)
    )
 
    create table PUBLIC.Role (
        id bigint generated by default as identity (start with 1),
        external_name varchar(255),
        name varchar(255) not null,
        note varchar(255),
        primary key (id)
    )
 
    create table PUBLIC.Servers (
        id integer not null,
        domain varchar(255) not null,
        mode varchar(255),
        port integer,
        primary key (id)
    )
 
    create table PUBLIC.Settings (
        id bigint generated by default as identity (start with 1),
        content varchar(255),
        parameter varchar(255) not null,
        primary key (id)
    )
 
    create table PUBLIC.SourceEntity (
        sourceId varchar(255) not null,
        sourceType varchar(255) not null,
        primary key (sourceId, sourceType)
    )
 
    create table PUBLIC.documents (
        id bigint generated by default as identity (start with 1),
        active_date bigint,
        category_id varchar(100),
        content clob(1048576),
        created_by varchar(255),
        date_created bigint,
        date_modified bigint,
        deleted boolean,
        description varchar(255),
        doc_id varchar(100),
        doc_type varchar(255),
        doc_url varchar(255),
        doc_name varchar(255),
        exp_date bigint,
        is_template boolean,
        modified_by varchar(255),
        status_id varchar(100),
        subcategory_id varchar(100),
        primary key (id)
    )
 
    create table PUBLIC.member_role (
        userid bigint not null,
        roleid bigint not null,
        primary key (userid, roleid)
    )
 
    create table PUBLIC.variables (
        id bigint generated by default as identity (start with 1),
        created_by varchar(255),
        date_created bigint,
        date_modified bigint,
        modified_by varchar(255),
        value varchar(255),
        varkey varchar(100) not null,
        primary key (id)
    )
 
    alter table PUBLIC.Member 
        add constraint UK_73pcydbur7ap0v0abheab5sfr unique (username)
 
    alter table PUBLIC.variables 
        add constraint UK_g86npvalrgjbior19e6tny5pp unique (varkey)
 
    alter table PUBLIC.CoherenceObjectEntity 
        add constraint FK_geewngu8owokforrxfje8iuxc 
        foreign key (property_id) 
        references PUBLIC.PropertyEntity
 
    alter table PUBLIC.EnvironmentEntity_InstanceEntity 
        add constraint FK_br4et9opxot999c7jp4y0u766 
        foreign key (instanceCollection_id) 
        references PUBLIC.InstanceEntity
 
    alter table PUBLIC.EnvironmentEntity_InstanceEntity 
        add constraint FK_58363fcyeggous7lsn1fcabsh 
        foreign key (environmentCollection_id) 
        references PUBLIC.EnvironmentEntity
 
    alter table PUBLIC.ExpressionEntity 
        add constraint FK_bwhisv1itl44ggwim8nuy499k 
        foreign key (source_sourceId, source_sourceType) 
        references PUBLIC.SourceEntity
 
    alter table PUBLIC.PropertyEntity 
        add constraint FK_8mb5sfbme9d64cb4hvw4mqf7b 
        foreign key (instance_id) 
        references PUBLIC.InstanceEntity
 
    alter table PUBLIC.member_role 
        add constraint FK_cvurj96c89600uemuy0s30w19 
        foreign key (roleid) 
        references PUBLIC.Role
 
    alter table PUBLIC.member_role 
        add constraint FK_3o322tcjgn3uglmqbbubb8obr 
        foreign key (userid) 
        references PUBLIC.Member
 
    create table PUBLIC.SEQUENCE_TABLE (
         SEQ_NAME varchar(255) not null ,
        SEQ_COUNT bigint,
        primary key ( SEQ_NAME ) 
    )